export const REGISTER = "REGISTER"
export const REGISTER_DATA_SENDING = "REGISTER_DATA_SENDING"

export const FETCHING_LOGIN_REQUEST = "FETCHING_LOGIN_REQUEST"
export const FETCHING_LOGIN_SUCESS = "FETCHING_LOGIN_SUCESS"
export const FETCHING_LOGIN_FAILURE = "FETCHING_LOGIN_FAILURE"
export const LOGOUT = "LOGOUT"
export const SEARCH_TOKEN = "SEARCH_TOKEN"

export const DELETE_CACHE = "DELETE_CACHE"

export const SET_CATEGORY = "SET_CATEGORY"
export const SEARCH_KEY_WORD = "SEARCH_KEY_WORD"

export const FETCHING_MENUS_REQUEST = "FETCHING_MENUS_REQUEST"
export const FETCHING_MENUS_SUCESS = "FETCHING_MENUS_SUCESS"
export const FETCHING_MENUS_FAILURE = "FETCHING_MENUS_FAILURE"

export const FETCHING_ORDER_REQUEST = "FETCHING_ORDER_REQUEST"
export const FETCHING_ORDER_SUCESS = "FETCHING_ORDER_SUCESS"
export const FETCHING_ORDER_FAILURE = "FETCHING_ORDER_FAILURE"
export const SET_TABLE_INFO= "SET_TABLE_INFO"
export const SET_ITEM  = "SET_ITEM"
export const SET_ORDER_PRICE = "SET_ORDER_PRICE"
export const REMOVE_ITEM = "REMOVE_ITEM"
